- type: local
  path: /home/manuel/Downloads/preview-and-recording-performance-improvement-diary.md
  lastFetched: 2026-04-14T13:45:02.781439137-04:00
- type: local
  path: /home/manuel/Downloads/preview-and-recording-performance-improvement-report.md
  lastFetched: 2026-04-14T13:45:02.856357444-04:00
